name: VideoMed
description: Server, admin, and client apps for controlling client video playlists.
dependencies:
  args: any
  html_components: any
  polymer: ">=0.10.0-pre.7 <0.11.0"
  polymer_elements: ">=0.2.0-pre.2 <0.3.0"
  route: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/admin.html
