name: videomed
description: Server, admin, and client apps for controlling client video playlists.
dependencies:
  args: any
  polymer: ">=0.11.0-dev.4"
  route: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/admin.html
