name: VideoMed
description: Server, admin, and client apps for controlling client video playlists.
dependencies:
  logging: any
  polymer: any
  route: any
transformers:
- polymer:
    entry_points: web/index.html
