name: VideoMed
description: Server, admin, and client apps for controlling client video playlists.
dependencies:
  args: any
#  html_components:
#    git:
#      url: git://github.com/szgabsz91/html-components.git
  polymer: ">=0.10.0-pre.12"
  polymer_elements: ">=0.2.0-pre.5"
  route: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/admin.html
